# Params controlling the simulation
force: False
dev: False
n_parallel: 1
random_seed: null

# For live simulation of data pipelines
live_sim: null

# Number of customers, growth and churn
init_customers: 10000
growth_rate: 0.1
acausal_churn: 0.0

# Customer satisfaction scaling
satisfy_scale: 1.5
satisfy_base: 2.0

# Customer age parameters
min_age: 12
max_age: 82
age_satisfy: 0.5

# Discounts
discount_prob: 0.0
min_discount: 0.05
max_discount: 0.5
discount_satisfy: 1.0

# Day of week event scaling
weekday_scale: -0.2
weekend_scale: 0.2

# Behavioral & Utility model
behave_exp_base: 1.6
util_contrib_scale: 2.0

# Stop hydra from changing dir and saving stuff
hydra:
  run:
    dir: .
  output_subdir: null
